# You should install `realtime-privileges` and run `sudo usermod -aG realtime $USER` if you are on arch linux.
# Consult the Project Readme if you are on another distribution
context.modules = [
    { name = libpipewire-module-rt
        args = {
            rt.prio      = 98
        }
        flags = [ ifexists nofail ]
    }
]

stream.properties = {
    node.latency          = 512/48000
}
