stream.properties = {
    resample.quality        = 10    # This can go as high as 15. However beyond 10 is likely placebo and uses more cpu than it's worth.
    channelmix.upmix        = false # Upmixing might be worth enabling if you use virtual surround.
    channelmix.upmix-method = psd   # Better default if `channelmix.upmix` is set to `true`.
    channelmix.stereo-widen = 0.0   # Enable if you want a fake but convincing soundstage boost.
    channelmix.normalize    = false # Set to 1 if you want to limit how varied volume is. Similar to a "Night Mode" in some cases.
    dither.noise            = 0     # Set to 1 if dithering sounds better to you

    # The options below make 0 sense for headphone usage. If you aren't using speakers you should probably ignore these
    channelmix.mix-lfe      = false
    channelmix.lfe-cutoff   = 0
    channelmix.fc-cutoff    = 0
    channelmix.rear-delay   = 0
    channelmix.hilbert-taps = 0
}
