context.modules = [
    {   name = libpipewire-module-echo-cancel
        flags = [ nofail ]
        args = {
            monitor.mode = true
            capture.props = {
                node.target = "alsa_input.usb-AKG_C44-USB_Microphone_AKG_C44-USB_Microphone-00.iec958-stereo"
                node.passive = true
            }
            sink.props = {
                node.target = "alsa_output.usb-CrinEar_Technology_Protocol_Max_330243CC251219-01.iec958-stereo"
            }
            source.props = {
                node.name = "output.ec_source"
                node.description = "Echo Cancelling"
            }
        }
    }
]
